# Generated by Django 5.0 on 2023-12-15 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_alter_api_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
